#!/usr/bin/env python3
"""SPEC-108 geometry probe — fast sliding-window N estimate.

Uses EQ adaptive thresholds (adaptive_chunking.rs) and a word/CJK token
heuristic aligned with recursive_token_len for stride estimates.

This is intentionally NOT a full RecursiveCharacterTextSplitter port —
full recursion on 60k+ char docs is too slow for a measurement script.
Labeled geometry-only; ratios A vs B are the signal (LAW-X2).
"""

from __future__ import annotations

import json
import math
import re
from dataclasses import asdict, dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT_DIR = Path(__file__).resolve().parent
CJK_RE = re.compile(r"[\u4e00-\u9fff\u3400-\u4dbf\u3000-\u303f]")


def adaptive_chunk_size(document_size_bytes: int) -> int:
    if document_size_bytes > 100_000:
        return 600
    if document_size_bytes > 50_000:
        return 800
    return 1200


def adaptive_overlap(chunk_size: int) -> int:
    return int(chunk_size * 0.083)


def recursive_token_len(text: str) -> int:
    trimmed = text.strip()
    if not trimmed:
        return 0
    cjk = len(CJK_RE.findall(trimmed))
    chars = len(trimmed)
    if cjk * 2 >= chars:
        base = max(1, math.ceil(chars / 1.5))
    else:
        words = [w for w in trimmed.split() if w]
        base = len(words) if words else max(1, chars // 4)
    return max(1, base)


def sliding_chunk_count(text: str, chunk_size: int, overlap: int) -> tuple[int, float]:
    """Stride estimate: total_tokens / (chunk_size - overlap)."""
    total = recursive_token_len(text)
    step = max(1, chunk_size - overlap)
    n = max(1, math.ceil(total / step)) if total else 0
    # mean ≈ min(chunk_size, total) for first; remaining full steps
    mean = float(min(chunk_size, total)) if total else 0.0
    return n, mean


@dataclass
class Row:
    arm: str
    sample_id: str
    path: str
    bytes: int
    chars: int
    total_tokens_est: int
    chunk_size_pin: int
    chunk_overlap: int
    chunk_count: int
    mean_chunk_tokens: float
    mode: str = "geometry-only-stride"


def arms_for_bytes(n_bytes: int) -> list[tuple[str, int, int]]:
    b_size = adaptive_chunk_size(n_bytes)
    return [
        ("A_eq_fair", 1200, 100),
        ("B_eq_product", b_size, adaptive_overlap(b_size)),
        ("C_lightrag", 1200, 100),
    ]


def measure_text(sample_id: str, path: Path) -> list[Row]:
    raw = path.read_bytes()
    text = path.read_text(encoding="utf-8", errors="replace")
    total = recursive_token_len(text)
    rows: list[Row] = []
    for arm, size, ov in arms_for_bytes(len(raw)):
        n, mean = sliding_chunk_count(text, size, ov)
        rows.append(
            Row(
                arm=arm,
                sample_id=sample_id,
                path=str(path.relative_to(ROOT)),
                bytes=len(raw),
                chars=len(text),
                total_tokens_est=total,
                chunk_size_pin=size,
                chunk_overlap=ov,
                chunk_count=n,
                mean_chunk_tokens=mean,
            )
        )
    return rows


def pdf_byte_pin(sample_id: str, path: Path) -> list[Row]:
    n = path.stat().st_size
    rows: list[Row] = []
    for arm, size, ov in arms_for_bytes(n):
        rows.append(
            Row(
                arm=arm,
                sample_id=sample_id,
                path=str(path.relative_to(ROOT)),
                bytes=n,
                chars=0,
                total_tokens_est=0,
                chunk_size_pin=size,
                chunk_overlap=ov,
                chunk_count=-1,
                mean_chunk_tokens=0.0,
                mode="geometry-only-pdf-bytes-pin",
            )
        )
    return rows


def to_markdown(rows: list[Row]) -> str:
    lines = [
        "# SPEC-108 geometry table",
        "",
        "> Generated by `geometry_probe.py` (stride estimator). Geometry-only.",
        "",
        "| arm | sample | bytes | chars | tokens_est | chunk_size | overlap | N | mode |",
        "|-----|--------|------:|------:|-----------:|-----------:|--------:|--:|------|",
    ]
    for r in rows:
        n = "n/a" if r.chunk_count < 0 else str(r.chunk_count)
        lines.append(
            f"| {r.arm} | {r.sample_id} | {r.bytes} | {r.chars} | {r.total_tokens_est} | "
            f"{r.chunk_size_pin} | {r.chunk_overlap} | {n} | {r.mode} |"
        )
    lines.extend(["", "## Ratios", ""])
    by_sample: dict[str, dict[str, Row]] = {}
    for r in rows:
        if r.chunk_count < 0:
            continue
        by_sample.setdefault(r.sample_id, {})[r.arm] = r
    for sid, m in by_sample.items():
        a, b, c = m.get("A_eq_fair"), m.get("B_eq_product"), m.get("C_lightrag")
        if a and b and a.chunk_count:
            lines.append(
                f"- **{sid}** B/A = {b.chunk_count / a.chunk_count:.3f} "
                f"(A={a.chunk_count} @1200, B={b.chunk_count} @{b.chunk_size_pin})"
            )
        if a and c:
            lines.append(f"- **{sid}** A vs C (both 1200/100): A={a.chunk_count}, C={c.chunk_count}")
    # partner envelope
    lines.extend(
        [
            "",
            "## Partner envelope (LAW-X2)",
            "",
            "Partner M=12367 ⇒ min chunks ≥ ceil(12367/40) = **309**.",
            "At adaptive 600 tok that is a large multi-hundred-page / dense PDF —",
            "consistent with product adaptive ON, not proof of merge failure.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    rows: list[Row] = []
    md = ROOT / "zz_test_docs/academic_papers/lighrag_2410.05779v3.pymupdf.gold.md"
    pdf = ROOT / "zz_test_docs/academic_papers/lighrag_2410.05779v3.pdf"
    if md.is_file():
        rows.extend(measure_text("S1-md", md))
    if pdf.is_file():
        rows.extend(pdf_byte_pin("S1", pdf))

    medical = Path.home() / ".cache/edgequake/bench001/graphrag-bench/Datasets/Corpus/medical.json"
    if medical.is_file():
        try:
            data = json.loads(medical.read_text(encoding="utf-8"))
            if isinstance(data, list) and data:
                first = data[0]
                text = first.get("context") or first.get("text") or first.get("content") or ""
                if isinstance(text, str) and text.strip():
                    tmp = OUT_DIR / "_s2_medical_one.txt"
                    tmp.write_text(text, encoding="utf-8")
                    rows.extend(measure_text("S2-medical-one", tmp))
        except Exception as e:  # noqa: BLE001
            print(f"warn: medical skip: {e}")

    # synthetic large text to illustrate >100KB adaptive 600
    synth = OUT_DIR / "_synth_200kb.txt"
    # ~200KB of repeating paragraphs
    para = (
        "LightRAG retrieval augmented generation knowledge graph entity relation "
        "chunking overlap tokens document ingestion pipeline. "
    )
    synth.write_text(para * (200_000 // len(para) + 1), encoding="utf-8")
    rows.extend(measure_text("S-synth-200kb", synth))

    out_json = OUT_DIR / "geometry_results.json"
    out_md = OUT_DIR / "geometry_table.md"
    out_json.write_text(json.dumps([asdict(r) for r in rows], indent=2), encoding="utf-8")
    out_md.write_text(to_markdown(rows), encoding="utf-8")
    print(to_markdown(rows))
    print(f"wrote {out_md}")


if __name__ == "__main__":
    main()
