apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgequake.api.serviceName" . }}
  namespace: {{ include "edgequake.namespace" . }}
  labels:
    {{- include "edgequake.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "edgequake.api.selectorLabels" . | nindent 4 }}
