#!/usr/bin/env python3
"""Generate SSOT dev port assignments for EdgeQuake (Makefile + WebUI).

Writes `.edgequake-dev-ports.env` at repo root. Sourced by `make dev` / `make dev-bg`
after user `.env` so PORT/BACKEND_PORT never collide with gps-backend, Docker, etc.

Preferred defaults (8090 / 3010) sit outside the usual 8080/3000 dev stack range.
"""

from __future__ import annotations

import pathlib
import sys

# Allow import when invoked as a script from repo root.
_SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from select_edgequake_port import choose_port  # noqa: E402

ROOT = _SCRIPT_DIR.parent
PORTS_ENV = ROOT / ".edgequake-dev-ports.env"
WEBUI_PORTS = ROOT / "edgequake_webui" / ".env.local.ports"


def write_ports(
    scan_window: int,
    preferred_backend: int,
    preferred_frontend: int,
) -> tuple[int, int]:
    backend = choose_port("backend", preferred_backend, scan_window)
    frontend = choose_port("frontend", preferred_frontend, scan_window)

    backend_url = f"http://127.0.0.1:{backend}"
    frontend_url = f"http://localhost:{frontend}"

    lines = [
        "# Auto-generated by scripts/sync_dev_ports.py — do not edit.",
        "# Sourced by Makefile dev targets; overrides .env PORT/BACKEND_PORT.",
        f"BACKEND_PORT={backend}",
        f"FRONTEND_PORT={frontend}",
        f"BACKEND_URL={backend_url.replace('127.0.0.1', 'localhost')}",
        f"FRONTEND_URL={frontend_url}",
        f"EDGEQUAKE_API_URL={backend_url}",
        f"NEXT_PUBLIC_API_URL={backend_url}",
        # PORT intentionally omitted — backend/frontend set their own PORT
        # was: f"PORT={backend}",
    ]
    PORTS_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")

    webui_lines = [
        "# Auto-generated — dev proxy target for Next.js (see scripts/sync_dev_ports.py).",
        f"EDGEQUAKE_API_URL={backend_url}",
    ]
    WEBUI_PORTS.write_text("\n".join(webui_lines) + "\n", encoding="utf-8")

    return backend, frontend


def main() -> int:
    preferred_backend = int(sys.argv[1]) if len(sys.argv) > 1 else 8090
    preferred_frontend = int(sys.argv[2]) if len(sys.argv) > 2 else 3010
    scan_window = int(sys.argv[3]) if len(sys.argv) > 3 else 20

    backend, frontend = write_ports(
        scan_window=scan_window,
        preferred_backend=preferred_backend,
        preferred_frontend=preferred_frontend,
    )

    print(f"BACKEND_PORT={backend}")
    print(f"FRONTEND_PORT={frontend}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
