//! Build script for edgequake-api — build metadata + OpenAPI path SSOT (SPEC-027 phase 15).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    emit_build_metadata();
    generate_openapi_paths_inc();
}

fn emit_build_metadata() {
    let build_timestamp = utc_now();
    println!("cargo:rustc-env=EDGEQUAKE_BUILD_TIMESTAMP={build_timestamp}");

    let git_hash = git_short_hash().unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=EDGEQUAKE_GIT_HASH={git_hash}");

    let git_branch = git_branch().unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=EDGEQUAKE_GIT_BRANCH={git_branch}");

    let build_number = build_timestamp
        .replace(['-', ':'], "")
        .replace('T', ".")
        .replace('Z', "");
    println!("cargo:rustc-env=EDGEQUAKE_BUILD_NUMBER={build_number}");

    println!("cargo:rustc-env=UTOIPA_PIN_VERSION=5.4.0");

    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/refs/");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/handlers");
}

/// Scan `src/handlers/**` for `#[utoipa::path]` + `pub async fn` and emit `openapi_paths.inc`.
///
/// SPEC-083 / X-25: also inventory `routes.rs` mounts against utoipa path strings so
/// annotated-but-unmounted (or mounted-but-undocumented) handlers fail the build.
fn generate_openapi_paths_inc() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("MANIFEST_DIR"));
    let handlers_root = manifest_dir.join("src/handlers");
    let openapi_rs = manifest_dir.join("src/openapi.rs");
    let routes_rs = manifest_dir.join("src/routes.rs");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("openapi_paths.inc");

    let mut entries = Vec::new();
    collect_utoipa_handlers(&handlers_root, &mut entries);

    entries.sort_by(|a, b| a.0.cmp(&b.0));
    entries.dedup_by(|a, b| a.1 == b.1);

    let generated: std::collections::BTreeSet<String> =
        entries.iter().map(|(_, fn_name)| fn_name.clone()).collect();

    let openapi_src = fs::read_to_string(&openapi_rs).expect("read openapi.rs");
    let registered = parse_openapi_registered_handlers(&openapi_src);

    let missing: Vec<_> = generated.difference(&registered).cloned().collect();
    let extra: Vec<_> = registered.difference(&generated).cloned().collect();
    if !missing.is_empty() || !extra.is_empty() {
        panic!(
            "OpenAPI path SSOT drift in openapi.rs paths():\n  missing handlers: {missing:?}\n  extra handlers: {extra:?}\n  generated={} registered={}",
            generated.len(),
            registered.len()
        );
    }

    // X-25: routes.rs path inventory ↔ utoipa `path = "..."` annotations.
    let routes_src = fs::read_to_string(&routes_rs).expect("read routes.rs");
    let route_paths = axum_route_paths(&routes_src);
    let utoipa_paths: std::collections::BTreeSet<String> = entries
        .iter()
        .map(|(path, _)| normalize_path_for_openapi(path))
        .collect();
    let missing_routes: Vec<_> = route_paths
        .iter()
        .filter(|p| !utoipa_paths.contains(*p))
        .cloned()
        .collect();
    let phantom_utoipa: Vec<_> = utoipa_paths
        .iter()
        .filter(|p| !route_paths.contains(*p))
        .cloned()
        .collect();
    if !missing_routes.is_empty() || !phantom_utoipa.is_empty() {
        panic!(
            "X-25 OpenAPI↔routes.rs path inventory drift:\n  mounted but missing utoipa path: {missing_routes:?}\n  utoipa path not mounted in routes.rs: {phantom_utoipa:?}\n  routes={} utoipa={}",
            route_paths.len(),
            utoipa_paths.len()
        );
    }

    let mut lines = String::from("// @generated by build.rs\n");
    for (_path, fn_name) in &entries {
        lines.push_str(&format!("handlers::{fn_name},\n"));
    }

    fs::write(&out_file, lines).expect("write openapi_paths.inc");
    write_path_count_assert(&out_dir, generated.len());
    println!("cargo:rerun-if-changed=src/openapi.rs");
    println!("cargo:rerun-if-changed=src/routes.rs");

    eprintln!(
        "edgequake-api build: OpenAPI SSOT OK — {} handler paths, {} routes.rs mounts",
        generated.len(),
        route_paths.len()
    );
}

fn normalize_path_for_openapi(path: &str) -> String {
    path.replace("{*", "{")
}

/// Extract `.route("...")` path literals from a function body (mirrors route_registry).
fn extract_route_literals(body: &str) -> Vec<String> {
    let mut paths = Vec::new();
    let mut search_from = 0;
    while let Some(rel) = body[search_from..].find(".route(") {
        let start = search_from + rel + ".route(".len();
        let rest = &body[start..];
        let Some(open) = rest.find('"') else {
            break;
        };
        let after_open = &rest[open + 1..];
        let Some(close) = after_open.find('"') else {
            break;
        };
        paths.push(after_open[..close].to_string());
        search_from = start + open + 1 + close + 1;
    }
    paths
}

fn function_body<'a>(src: &'a str, fn_name: &str) -> Option<&'a str> {
    let needle = format!("fn {fn_name}");
    let start = src.find(&needle)?;
    let after = &src[start..];
    let open = after.find('{')? + 1;
    let body_start = start + open;
    let mut depth = 1usize;
    let mut i = body_start;
    let bytes = src.as_bytes();
    while i < bytes.len() && depth > 0 {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => depth -= 1,
            _ => {}
        }
        i += 1;
    }
    if depth == 0 {
        Some(&src[body_start..i - 1])
    } else {
        None
    }
}

/// All HTTP paths registered in `routes.rs` (deduplicated, OpenAPI-normalized).
fn axum_route_paths(routes_rs: &str) -> std::collections::BTreeSet<String> {
    let mut paths = std::collections::BTreeSet::new();

    for fn_name in &["create_router", "create_router_inner"] {
        if let Some(body) = function_body(routes_rs, fn_name) {
            for path in extract_route_literals(body) {
                paths.insert(normalize_path_for_openapi(&path));
            }
        }
    }
    if let Some(body) = function_body(routes_rs, "mcp_routes") {
        for path in extract_route_literals(body) {
            paths.insert(normalize_path_for_openapi(&path));
        }
    }
    if let Some(body) = function_body(routes_rs, "ollama_api_routes") {
        for path in extract_route_literals(body) {
            paths.insert(normalize_path_for_openapi(&format!("/api{path}")));
        }
    }
    if let Some(body) = function_body(routes_rs, "api_v1_routes") {
        for path in extract_route_literals(body) {
            paths.insert(normalize_path_for_openapi(&format!("/api/v1{path}")));
        }
    }
    if let Some(body) = function_body(routes_rs, "api_v2_routes") {
        for path in extract_route_literals(body) {
            paths.insert(normalize_path_for_openapi(&format!("/api/v2{path}")));
        }
    }
    paths
}

fn parse_openapi_registered_handlers(openapi_src: &str) -> std::collections::BTreeSet<String> {
    let Some(start) = openapi_src.find("paths(") else {
        return std::collections::BTreeSet::new();
    };
    let Some(end) = openapi_src[start..].find("components(") else {
        return std::collections::BTreeSet::new();
    };
    let block = &openapi_src[start..start + end];

    let mut names = std::collections::BTreeSet::new();
    for line in block.lines() {
        let trimmed = line.trim();
        if !trimmed.starts_with("handlers::") {
            continue;
        }
        let path = trimmed.trim_end_matches(',');
        let fn_name = path.rsplit("::").next().unwrap_or(path);
        names.insert(fn_name.to_string());
    }
    names
}

/// Recursively collect utoipa handlers from COMPILED modules only.
///
/// SSOT is the compiled handler surface: a `.rs` file on disk that no `mod`
/// declaration reaches is not part of the crate (e.g. in-flight untracked
/// work) and must not fail the OpenAPI gate. At each directory we read
/// `mod.rs` for `mod <name>;` declarations; undeclared files/subdirs are
/// skipped. Directories without `mod.rs` fall back to full scanning.
fn collect_utoipa_handlers(dir: &Path, out: &mut Vec<(String, String)>) {
    let declared = declared_modules(dir);
    let Ok(read_dir) = fs::read_dir(dir) else {
        return;
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
        if path.is_dir() {
            if declared.as_ref().is_none_or(|d| d.contains(stem)) {
                collect_utoipa_handlers(&path, out);
            }
        } else if path.extension().is_some_and(|e| e == "rs") {
            let is_mod_rs = path.file_name().and_then(|s| s.to_str()) == Some("mod.rs");
            if !is_mod_rs && declared.as_ref().is_some_and(|d| !d.contains(stem)) {
                continue;
            }
            if let Ok(src) = fs::read_to_string(&path) {
                out.extend(parse_utoipa_handlers(&src));
            }
        }
    }
}

/// Parse `mod <name>;` declarations from a directory's `mod.rs`.
/// Returns `None` when no `mod.rs` exists (caller scans unfiltered).
fn declared_modules(dir: &Path) -> Option<std::collections::BTreeSet<String>> {
    let src = fs::read_to_string(dir.join("mod.rs")).ok()?;
    let mut names = std::collections::BTreeSet::new();
    for raw in src.lines() {
        let line = raw.trim();
        // Skip comments and non-module items; match `pub mod x;` / `mod x;`.
        let line = line.split("//").next().unwrap_or("").trim();
        for token in ["pub mod ", "pub(crate) mod ", "mod "] {
            if let Some(rest) = line.strip_prefix(token) {
                let name: String = rest
                    .trim_end_matches([';', '{'])
                    .trim()
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    names.insert(name);
                }
                break;
            }
        }
    }
    Some(names)
}

/// Extract `(openapi_path, fn_name)` pairs from handler source.
fn parse_utoipa_handlers(src: &str) -> Vec<(String, String)> {
    let mut found = Vec::new();
    let mut search = 0;
    while let Some(rel) = src[search..].find("#[utoipa::path") {
        let start = search + rel;
        let chunk = safe_prefix(&src[start..], 4096);
        let path = extract_quoted_after(chunk, "path = \"");
        let fn_name = extract_fn_name(chunk);
        if let (Some(path), Some(fn_name)) = (path, fn_name) {
            found.push((path, fn_name));
        }
        search = start + 1;
    }
    found
}

fn safe_prefix(s: &str, max_bytes: usize) -> &str {
    let mut end = max_bytes.min(s.len());
    while end > 0 && !s.is_char_boundary(end) {
        end -= 1;
    }
    &s[..end]
}

fn extract_quoted_after(haystack: &str, needle: &str) -> Option<String> {
    let start = haystack.find(needle)? + needle.len();
    let rest = &haystack[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn extract_fn_name(chunk: &str) -> Option<String> {
    for line in chunk.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("pub async fn ") {
            let name: String = rest
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                return Some(name);
            }
        }
    }
    None
}

fn write_path_count_assert(out_dir: &Path, generated_count: usize) {
    let check = format!(
        r#"// @generated compile-time OpenAPI path count SSOT
pub const OPENAPI_GENERATED_HANDLER_COUNT: usize = {generated_count};
"#
    );
    fs::write(out_dir.join("openapi_path_count.rs"), check).expect("write path count");
}

fn utc_now() -> String {
    let output = Command::new("date")
        .args(["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .output();
    match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        _ => "unknown".to_string(),
    }
}

fn git_short_hash() -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()?;
    if output.status.success() {
        Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        None
    }
}

fn git_branch() -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()
        .ok()?;
    if output.status.success() {
        Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_finds_path_and_fn() {
        let src = r#"
        #[utoipa::path(get, path = "/health", tag = "Health")]
        pub async fn health_check() {}
        "#;
        let v = parse_utoipa_handlers(src);
        assert_eq!(v, vec![("/health".to_string(), "health_check".to_string())]);
    }

    #[test]
    fn contract_x_25_axum_route_paths_normalize_catch_all() {
        let src = r#"
        fn create_router_inner() {
            Router::new().route("/ws/pipeline/progress", get(h));
        }
        fn api_v1_routes() {
            Router::new().route("/documents/{*path}", get(h));
        }
        "#;
        let paths = axum_route_paths(src);
        assert!(paths.contains("/ws/pipeline/progress"));
        assert!(paths.contains("/api/v1/documents/{path}"));
    }
}
